CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, employee_code VARCHAR(50) NULL UNIQUE, phone VARCHAR(30) NULL, profile_photo VARCHAR(255) NULL, email_verified_at DATETIME NULL, is_active TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(100) NOT NULL UNIQUE, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL UNIQUE, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS role_user (role_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(role_id,user_id));

CREATE TABLE IF NOT EXISTS permission_role (permission_id INTEGER NOT NULL, role_id INTEGER NOT NULL, PRIMARY KEY(permission_id,role_id));

CREATE TABLE IF NOT EXISTS countries (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL UNIQUE, iso_code VARCHAR(3) NOT NULL UNIQUE, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS states (id INTEGER PRIMARY KEY AUTOINCREMENT, country_id INTEGER NOT NULL, name VARCHAR(120) NOT NULL, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, UNIQUE(country_id,name));

CREATE TABLE IF NOT EXISTS cities (id INTEGER PRIMARY KEY AUTOINCREMENT, country_id INTEGER NOT NULL, state_id INTEGER NOT NULL, name VARCHAR(120) NOT NULL, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL, UNIQUE(state_id,name));

CREATE TABLE IF NOT EXISTS address_types (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL UNIQUE, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS units (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL, code VARCHAR(20) NOT NULL UNIQUE, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS taxes (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL UNIQUE, rate DECIMAL(5,2) NOT NULL DEFAULT 0, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS currencies (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL, code CHAR(3) NOT NULL UNIQUE, symbol VARCHAR(8) NOT NULL, exchange_rate DECIMAL(15,6) DEFAULT 1, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS quotation_statuses (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR(120) NOT NULL UNIQUE, slug VARCHAR(120) NOT NULL UNIQUE, color VARCHAR(20) NOT NULL, sort_order INTEGER DEFAULT 0, is_final TINYINT DEFAULT 0, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS company_settings (id INTEGER PRIMARY KEY AUTOINCREMENT, company_name VARCHAR(190) NOT NULL, gst_number VARCHAR(40) NULL, pan_number VARCHAR(20) NULL, email VARCHAR(190) NULL, mobile VARCHAR(30) NULL, website VARCHAR(190) NULL, address_line_1 VARCHAR(255) NULL, address_line_2 VARCHAR(255) NULL, country_id INTEGER NULL, state_id INTEGER NULL, city_id INTEGER NULL, postal_code VARCHAR(20) NULL, logo_path VARCHAR(255) NULL, is_active TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS bank_details (id INTEGER PRIMARY KEY AUTOINCREMENT, company_setting_id INTEGER NULL, bank_name VARCHAR(190) NOT NULL, account_name VARCHAR(190) NOT NULL, account_number VARCHAR(80) NOT NULL, ifsc VARCHAR(30) NULL, branch VARCHAR(120) NULL, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_code VARCHAR(60) NOT NULL UNIQUE, company_name VARCHAR(190) NOT NULL, contact_person VARCHAR(120) NULL, email VARCHAR(190) NULL, mobile VARCHAR(30) NULL, gst_number VARCHAR(40) NULL, pan_number VARCHAR(20) NULL, country_id INTEGER NULL, state_id INTEGER NULL, city_id INTEGER NULL, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS customer_addresses (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, address_type_id INTEGER NOT NULL, address_line_1 VARCHAR(255) NOT NULL, address_line_2 VARCHAR(255) NULL, country_id INTEGER NULL, state_id INTEGER NULL, city_id INTEGER NULL, postal_code VARCHAR(20) NULL, is_default TINYINT DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, product_code VARCHAR(60) NOT NULL UNIQUE, product_name VARCHAR(190) NOT NULL, description TEXT NULL, category VARCHAR(120) NULL, unit_id INTEGER NULL, hsn_code VARCHAR(40) NULL, tax_id INTEGER NULL, base_price DECIMAL(15,2) DEFAULT 0, image_path VARCHAR(255) NULL, status TINYINT DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS quotations (id INTEGER PRIMARY KEY AUTOINCREMENT, quotation_number VARCHAR(80) NOT NULL UNIQUE, customer_id INTEGER NOT NULL, quotation_date DATE NOT NULL, valid_till DATE NULL, sales_person_id INTEGER NULL, currency_id INTEGER NULL, quotation_status_id INTEGER NULL, sub_total DECIMAL(15,2) DEFAULT 0, item_discount_total DECIMAL(15,2) DEFAULT 0, global_discount_type VARCHAR(20) DEFAULT "fixed", global_discount_value DECIMAL(15,2) DEFAULT 0, global_discount_amount DECIMAL(15,2) DEFAULT 0, tax_total DECIMAL(15,2) DEFAULT 0, grand_total DECIMAL(15,2) DEFAULT 0, notes TEXT NULL, terms_conditions TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, deleted_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS quotation_items (id INTEGER PRIMARY KEY AUTOINCREMENT, quotation_id INTEGER NOT NULL, product_id INTEGER NULL, product_code_snapshot VARCHAR(80) NULL, description TEXT NOT NULL, quantity DECIMAL(12,3) DEFAULT 1, unit_id INTEGER NULL, rate DECIMAL(15,2) DEFAULT 0, discount_type VARCHAR(20) DEFAULT "fixed", discount_value DECIMAL(15,2) DEFAULT 0, discount_amount DECIMAL(15,2) DEFAULT 0, tax_id INTEGER NULL, tax_rate_snapshot DECIMAL(5,2) DEFAULT 0, tax_amount DECIMAL(15,2) DEFAULT 0, line_total DECIMAL(15,2) DEFAULT 0, sort_order INTEGER DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS quotation_attachments (id INTEGER PRIMARY KEY AUTOINCREMENT, quotation_id INTEGER NOT NULL, file_name VARCHAR(190) NOT NULL, file_path VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NULL, size INTEGER NULL, created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS follow_ups (id INTEGER PRIMARY KEY AUTOINCREMENT, quotation_id INTEGER NOT NULL, assigned_to INTEGER NULL, due_at DATETIME NOT NULL, notes TEXT NULL, status VARCHAR(20) DEFAULT "pending", created_at DATETIME NULL, updated_at DATETIME NULL);

CREATE TABLE IF NOT EXISTS activity_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NULL, event VARCHAR(80) NOT NULL, subject_type VARCHAR(120) NULL, subject_id INTEGER NULL, old_values TEXT NULL, new_values TEXT NULL, ip_address VARCHAR(80) NULL, user_agent VARCHAR(500) NULL, created_at DATETIME NULL);
