<?php
namespace App\Controllers;
use App\Repositories\TableRepository; use App\Support\Auth; use App\Support\Flash;
class MasterController
{ private array $map=['countries'=>['name'=>'Countries','table'=>'countries','fields'=>['name'=>['label'=>'Name'],'iso_code'=>['label'=>'ISO Code'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name','iso_code']], 'states'=>['name'=>'States','table'=>'states','fields'=>['country_id'=>['label'=>'Country ID','type'=>'number'],'name'=>['label'=>'Name'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name']], 'cities'=>['name'=>'Cities','table'=>'cities','fields'=>['country_id'=>['label'=>'Country ID','type'=>'number'],'state_id'=>['label'=>'State ID','type'=>'number'],'name'=>['label'=>'Name'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name']], 'address-types'=>['name'=>'Address Types','table'=>'address_types','fields'=>['name'=>['label'=>'Name'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name']], 'units'=>['name'=>'Units','table'=>'units','fields'=>['name'=>['label'=>'Name'],'code'=>['label'=>'Code'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name','code']], 'taxes'=>['name'=>'Taxes','table'=>'taxes','fields'=>['name'=>['label'=>'Name'],'rate'=>['label'=>'Rate','type'=>'number'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name']], 'currencies'=>['name'=>'Currencies','table'=>'currencies','fields'=>['name'=>['label'=>'Name'],'code'=>['label'=>'Code'],'symbol'=>['label'=>'Symbol'],'exchange_rate'=>['label'=>'Exchange Rate','type'=>'number'],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name','code']], 'quotation-statuses'=>['name'=>'Quotation Statuses','table'=>'quotation_statuses','fields'=>['name'=>['label'=>'Name'],'slug'=>['label'=>'Slug'],'color'=>['label'=>'Color'],'sort_order'=>['label'=>'Sort','type'=>'number'],'is_final'=>['label'=>'Final','type'=>'select','options'=>[0=>'No',1=>'Yes']],'status'=>['label'=>'Status','type'=>'select','options'=>[1=>'Active',0=>'Inactive']]],'search'=>['name','slug']]];
 private function cfg(string $type): array { if(!isset($this->map[$type])) { http_response_code(404); exit('Unknown master'); } return $this->map[$type]; }
 public function index(string $type): string { Auth::requirePermission('masters.view'); $c=$this->cfg($type); $rows=(new TableRepository($c['table']))->paginate($_GET['search']??'', $c['search']); return view('partials.crud',['mode'=>'index','rows'=>$rows,'fields'=>$c['fields'],'module'=>'masters/'.$type,'title'=>$c['name']]); }
 public function create(string $type): string { Auth::requirePermission('masters.create'); $c=$this->cfg($type); return view('partials.crud',['mode'=>'form','row'=>[],'fields'=>$c['fields'],'module'=>'masters/'.$type,'title'=>'Create '.$c['name']]); }
 public function store(string $type): never { Auth::requirePermission('masters.create'); $c=$this->cfg($type); (new TableRepository($c['table']))->create($this->payload($c)); Flash::set('success','Master saved.'); redirect('/masters/'.$type); }
 public function edit(string $type,int $id): string { Auth::requirePermission('masters.edit'); $c=$this->cfg($type); return view('partials.crud',['mode'=>'form','row'=>(new TableRepository($c['table']))->find($id),'fields'=>$c['fields'],'module'=>'masters/'.$type,'title'=>'Edit '.$c['name']]); }
 public function update(string $type,int $id): never { Auth::requirePermission('masters.edit'); $c=$this->cfg($type); (new TableRepository($c['table']))->update($id,$this->payload($c)); Flash::set('success','Master updated.'); redirect('/masters/'.$type); }
 public function toggle(string $type,int $id): never { Auth::requirePermission('masters.edit'); $c=$this->cfg($type); $repo=new TableRepository($c['table']); $row=$repo->find($id); $repo->update($id,['status'=>empty($row['status'])?1:0]); redirect('/masters/'.$type); }
 public function delete(string $type,int $id): never { Auth::requirePermission('masters.delete'); $c=$this->cfg($type); (new TableRepository($c['table']))->softDelete($id); Flash::set('success','Master deleted.'); redirect('/masters/'.$type); }
 private function payload(array $c): array { $d=[]; foreach($c['fields'] as $k=>$v) $d[$k]=$_POST[$k]??null; return $d; }}
