<?php
namespace App\Controllers;
use App\Core\Database; use App\Repositories\TableRepository; use App\Services\QuotationCalculationService; use App\Services\QuotationNumberService; use App\Support\Audit; use App\Support\Auth; use App\Support\Flash;
class QuotationController
{ public function index(): string { Auth::requirePermission('quotations.view'); $rows=Database::connect()->query('SELECT q.*, c.company_name, s.name status_name FROM quotations q JOIN customers c ON c.id=q.customer_id LEFT JOIN quotation_statuses s ON s.id=q.quotation_status_id WHERE q.deleted_at IS NULL ORDER BY q.id DESC LIMIT 50')->fetchAll(); return view('quotations.index', compact('rows')); }
 public function create(): string { Auth::requirePermission('quotations.create'); return $this->form([]); }
 public function edit(int $id): string { Auth::requirePermission('quotations.edit'); $q=(new TableRepository('quotations'))->find($id); return $this->form($q ?: [], $id); }
 private function form(array $row, ?int $id=null): string { $db=Database::connect(); $customers=$db->query('SELECT id, company_name FROM customers WHERE deleted_at IS NULL ORDER BY company_name')->fetchAll(); $products=$db->query('SELECT p.*, t.rate tax_rate FROM products p LEFT JOIN taxes t ON t.id=p.tax_id WHERE p.deleted_at IS NULL ORDER BY product_name')->fetchAll(); $items=$id ? $db->query('SELECT * FROM quotation_items WHERE quotation_id='.(int)$id.' ORDER BY sort_order')->fetchAll() : []; $statuses=$db->query('SELECT * FROM quotation_statuses ORDER BY sort_order')->fetchAll(); $currencies=$db->query('SELECT * FROM currencies ORDER BY code')->fetchAll(); return view('quotations.form', compact('row','customers','products','items','statuses','currencies')); }
 public function store(): never { Auth::requirePermission('quotations.create'); $this->save(); }
 public function update(int $id): never { Auth::requirePermission('quotations.edit'); $this->save($id); }
 private function save(?int $id=null): never { $db=Database::connect(); $items=$this->items(); $calc=(new QuotationCalculationService())->calculate($items, $_POST['global_discount_type']??'fixed', (float)($_POST['global_discount_value']??0)); $data=['quotation_number'=>$_POST['quotation_number'] ?: (new QuotationNumberService())->next(),'customer_id'=>(int)$_POST['customer_id'],'quotation_date'=>$_POST['quotation_date'] ?: date('Y-m-d'),'valid_till'=>$_POST['valid_till'] ?: null,'sales_person_id'=>Auth::id(),'currency_id'=>(int)($_POST['currency_id']??1),'quotation_status_id'=>(int)($_POST['quotation_status_id']??1),'global_discount_type'=>$_POST['global_discount_type']??'fixed','global_discount_value'=>(float)($_POST['global_discount_value']??0),'notes'=>$_POST['notes']??'','terms_conditions'=>$_POST['terms_conditions']??'']; $data += array_intersect_key($calc, array_flip(['sub_total','item_discount_total','global_discount_amount','tax_total','grand_total'])); $repo=new TableRepository('quotations'); if($id){$repo->update($id,$data); $db->prepare('DELETE FROM quotation_items WHERE quotation_id=?')->execute([$id]);} else {$id=$repo->create($data);} foreach($calc['items'] as $item){$item['quotation_id']=$id; (new TableRepository('quotation_items'))->create($item);} Audit::log($id?'quotation_saved':'quotation_created','quotations',$id,[],$data); Flash::set('success','Quotation saved.'); redirect('/quotations'); }
 private function items(): array { $items=[]; foreach(($_POST['description']??[]) as $i=>$desc){ if(trim($desc)==='') continue; $items[]=['product_id'=>(int)($_POST['product_id'][$i]??0) ?: null,'product_code_snapshot'=>$_POST['product_code_snapshot'][$i]??'','description'=>$desc,'quantity'=>(float)($_POST['quantity'][$i]??1),'unit_id'=>(int)($_POST['unit_id'][$i]??0) ?: null,'rate'=>(float)($_POST['rate'][$i]??0),'discount_type'=>$_POST['discount_type'][$i]??'fixed','discount_value'=>(float)($_POST['discount_value'][$i]??0),'tax_id'=>(int)($_POST['tax_id'][$i]??0) ?: null,'tax_rate_snapshot'=>(float)($_POST['tax_rate_snapshot'][$i]??0)]; } return $items ?: [['description'=>'Furniture item','quantity'=>1,'rate'=>0,'tax_rate_snapshot'=>0]]; }
 public function delete(int $id): never { Auth::requirePermission('quotations.delete'); (new TableRepository('quotations'))->softDelete($id); redirect('/quotations'); }
 public function send(int $id): never { $this->status($id,'sent'); }
 public function approve(int $id): never { Auth::requirePermission('quotations.approve'); $this->status($id,'approved'); }
 public function reject(int $id): never { Auth::requirePermission('quotations.approve'); $this->status($id,'rejected'); }
 private function status(int $id,string $slug): never { $db=Database::connect(); $sid=(int)$db->query("SELECT id FROM quotation_statuses WHERE slug='".$slug."'")->fetchColumn(); $db->prepare('UPDATE quotations SET quotation_status_id=?, updated_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$sid,$id]); Audit::log('status_'.$slug,'quotations',$id); redirect('/quotations'); }
 public function duplicate(int $id): never { Auth::requirePermission('quotations.create'); $db=Database::connect(); $q=(new TableRepository('quotations'))->find($id); unset($q['id']); $q['quotation_number']=(new QuotationNumberService())->next(); $q['quotation_status_id']=1; $new=(new TableRepository('quotations'))->create($q); foreach($db->query('SELECT * FROM quotation_items WHERE quotation_id='.(int)$id)->fetchAll() as $it){unset($it['id']);$it['quotation_id']=$new;(new TableRepository('quotation_items'))->create($it);} redirect('/quotations/'.$new.'/edit'); }
 public function pdf(int $id): string { Auth::requirePermission('quotations.view'); $db=Database::connect(); $q=$db->query('SELECT q.*, c.company_name,c.email,c.mobile FROM quotations q JOIN customers c ON c.id=q.customer_id WHERE q.id='.(int)$id)->fetch(); $items=$db->query('SELECT * FROM quotation_items WHERE quotation_id='.(int)$id.' ORDER BY sort_order')->fetchAll(); $company=$db->query('SELECT * FROM company_settings ORDER BY id DESC LIMIT 1')->fetch(); return view('quotations.pdf', ['layout'=>false,'q'=>$q,'items'=>$items,'company'=>$company]); }}
